### ISSUE TITLE
Show password strength on Signup Page

### ISSUE THREAD

**Issue by dhanrajchaurasia** [ContriHUB/CP-Grind#4]
### Show the password strength on the signup page
Show the password strength with 4 levels (very weak, weak, strong, very strong) also display the stuff to improve the strength like the following:
- Password should be at least 8 characters
- It should contain at least one upper-case letter.
- It should contain at least one lowercase letter.
- It should contain at least one digit.
- It should contain at least one special character.

**Comment by RKOsvk** [comment]
Can I start work on this issue? Can you assign me?

**Comment by dhanrajchaurasia** [comment]
> Can I start work on this issue? Can you assign me?

you should request the issue from Contrihub website and also do locally setup the project you are requesting for
